name: planalto_automacao_ia
description: IA para automação industrial e residencial
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  pdf: ^3.10.7
  printing: ^5.12.0

flutter:
  uses-material-design: true
