name: Generate Keystore (ONE TIME)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Android keystore
        run: |
          keytool -genkeypair \
            -keystore planalto-release.keystore \
            -storepass 123456 \
            -keypass 123456 \
            -alias planalto \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Planalto Automacao, OU=Planalto, O=Planalto, L=Cidade, S=Estado, C=BR"

      - name: Convert keystore to base64
        run: |
          base64 planalto-release.keystore > keystore.txt

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: planalto-keystore
          path: keystore.txt
